// Which Bellarmine clubs could actually meet at a place, from
// src/lib/bellarmine.json.
//
// Generated by scripts/sync-bellarmine.mjs from bcp.org's own clubs page and
// committed like the catalogue and the events file, so there is no key in the
// bundle and no request at render time.
//
// The join is done in the generator, against the city's amenity codes and
// interests — a club is here because San José publishes that this park has
// the pickleball courts the Pickleball Club plays on, not because anything
// guessed. 38 of the 79 clubs match nothing in the city's data and appear on
// no place at all, which is the honest reading of a roster that contains
// Thrifting Club and Trader Joe's Enthusiasts Club.
//
// Nothing here touches a score. Like events and interests, it filters and
// labels; the five components stay what they were.

import data from "./bellarmine.json";
import { milesBetween } from "./scoring";

export const BELLARMINE_SOURCE = data.source;
export const BELLARMINE_URL = data.url;
export const BELLARMINE_GENERATED = data.generated;

/** 960 W Hedding St, for "1.4 mi from campus" — the walk a reader actually makes. */
export const CAMPUS = data.campus;

/** 79 clubs listed, 41 of which have somewhere off campus to be. */
export const CLUB_COUNT = data.count;
export const PLACED_COUNT = data.placed;

/** Places hosting at least one club — what the Bellarmine filter leaves on the map. */
export const CLUB_PLACES = data.places;

const byId = new Map(data.clubs.map((club) => [club.id, club]));

/**
 * The clubs this place could host, grouped by what brought them here and
 * alphabetical inside each group.
 *
 * Grouped rather than by the school's own categories, which are a filing
 * system for a web page and not anything a reader thinks in. Grouping by
 * reason is also what lets the detail screen print "game tables" once above
 * the eight clubs that want them instead of once per row.
 */
export function clubsFor(slug) {
  const ids = data.by_slug[slug];
  if (!ids) return [];
  return ids
    .map((id) => byId.get(id))
    .sort(
      (a, b) =>
        (reasonFor(a) ?? "").localeCompare(reasonFor(b) ?? "") || a.name.localeCompare(b.name)
    );
}

export function hostsClubs(slug) {
  return Boolean(data.by_slug[slug]);
}

const AMENITY_REASONS = {
  PICKLE: "pickleball courts",
  SKATE: "a skate park",
  VOLL: "volleyball courts",
  FUTSAL: "futsal courts",
  GAMETB: "game tables",
  PNGPNG: "table tennis",
};

/**
 * Why this place matched — "pickleball courts" rather than "PICKLE".
 *
 * A club can want a place for more than one reason, but only one of them is
 * ever the interesting one, so this reports the first.
 */
export function reasonFor(club) {
  const need = club.needs[0];
  if (!need) return null;
  return need.via === "amenity" ? AMENITY_REASONS[need.value] : "somewhere to sit and talk";
}

/** Straight-line miles from campus, or null when the place has no fix. */
export function milesFromCampus(place) {
  return milesBetween(CAMPUS, place);
}
