// What is actually on at a place, from src/lib/events.json.
//
// Generated by scripts/sync-events.mjs from San José Public Library's own
// events service and committed like the catalogue, so there is no key in the
// bundle and no request at render time. Only libraries have a feed today, so
// most places have nothing here and show nothing — an absent list is normal,
// not a failure.
//
// The file is a build input with absolute timestamps in it, so it starts going
// stale the moment it is written. Everything below re-checks against the
// current clock rather than trusting that the build was recent.

import data from "./events.json";

const DAY = 86400000;

/** When the feed was last pulled, for the about line. */
export const EVENTS_GENERATED = data.generated;

export const EVENTS_SOURCE = data.source;

/**
 * Upcoming events at a place, soonest first. Anything that has already started
 * is dropped: a build from this morning still lists this morning's story time,
 * and showing it would be the same kind of lie as a hand-typed opening hour.
 */
export function eventsFor(slug, limit = 0) {
  const all = data.by_slug[slug];
  if (!all) return [];
  const now = Date.now();
  const upcoming = all.filter((event) => Date.parse(event.start) >= now);
  return limit ? upcoming.slice(0, limit) : upcoming;
}

export function nextEvent(slug) {
  return eventsFor(slug, 1)[0] ?? null;
}

/**
 * "Today 6:30 PM", "Tomorrow 10:00 AM", "Sat 2:00 PM", "Aug 24, 2:00 PM".
 *
 * Local time, which for this catalogue is the reader's own — every place in it
 * is in San José, so there is no zone to reconcile.
 */
export function whenLabel(iso) {
  const at = new Date(iso);
  const time = at.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" });

  // Compare calendar days rather than elapsed hours, so an event at 11pm
  // tonight doesn't read as "Tomorrow" just because it is more than a day off.
  const midnight = new Date();
  midnight.setHours(0, 0, 0, 0);
  const days = Math.floor((at - midnight) / DAY);

  if (days <= 0) return `Today ${time}`;
  if (days === 1) return `Tomorrow ${time}`;
  if (days < 7) return `${at.toLocaleDateString([], { weekday: "short" })} ${time}`;
  return `${at.toLocaleDateString([], { month: "short", day: "numeric" })}, ${time}`;
}
