// Answering "where are you?" without asking Google.
//
// Generated by scripts/sync-geography.mjs from the Census Bureau's TIGERweb
// service: 98 ZIP codes and 78 towns across the South Bay, plus the city's
// own planning areas out of the catalogue. Re-generate rather than edit:
//
//   node scripts/sync-geography.mjs
//
// This used to be thirteen names. The address field's only offline fallback
// was `NEIGHBORHOODS` — Willow Glen, Almaden, Berryessa and ten more — so a
// reader in Mountain View matched nothing, and a reader who typed a ZIP
// matched nothing, on a field captioned "e.g. Japantown or 95112". Both are
// ordinary answers to the question, and neither one worked.
//
// It is also the fast path, not only the fallback. A ZIP or a town name is
// answered from this file in a keystroke with no request at all, which is
// both quicker than a round trip to Places and one less billable call.

import data from "./geography.json";
import { NEIGHBORHOODS } from "./seed";

export const GEOGRAPHY_SOURCE = data.source;
export const GEOGRAPHY_GENERATED = data.generated;
export const CITIES = data.cities;
export const ZIPS = data.zips;

const LIMIT = 6;

/** Lowercased and stripped of accents, so "san jose" finds "San José". */
function fold(value) {
  return (value ?? "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .trim();
}

/** True when the whole query is digits — a ZIP being typed, complete or not. */
export function looksLikeZip(query) {
  return /^\d{1,5}$/.test(query.trim());
}

// A suggestion the app can act on without another call: the point is already
// here, and `location` is the line that gets written to the profile.
function entry(id, main, secondary, point, location) {
  return { id, main, secondary, point: { lat: point.lat, lng: point.lng }, location };
}

function districtEntries() {
  return NEIGHBORHOODS.map((n) =>
    entry(`district:${n.name}`, n.name, "San José", n, `${n.name}, San José`)
  );
}

function zipEntries() {
  return ZIPS.map((z) =>
    entry(
      `zip:${z.zip}`,
      z.zip,
      z.city ?? "Santa Clara County",
      z,
      z.city ? `${z.zip}, ${z.city}` : z.zip
    )
  );
}

function cityEntries() {
  return CITIES.map((c) =>
    entry(`city:${c.name}`, c.name, c.incorporated ? "City" : "Community", c, c.name)
  );
}

/**
 * Everything here that matches what has been typed, best first.
 *
 * Order is deliberate and not by string quality. A San José district is the
 * finest-grained answer and the one the catalogue is built around, so it
 * leads; a ZIP is exact; a town is the coarsest. Within each kind, a name
 * that *starts* with the query beats one that merely contains it, because
 * "los" should offer Los Gatos and Los Altos before Palo Alto.
 */
export function lookupPlaces(query) {
  const q = fold(query);
  if (q.length < 2) return [];

  // A run of digits is a ZIP and nothing else — no town here is named 951.
  if (looksLikeZip(query)) {
    return zipEntries()
      .filter((e) => e.main.startsWith(q))
      .slice(0, LIMIT);
  }

  const groups = [districtEntries(), zipEntries(), cityEntries()];
  const found = [];

  for (const group of groups) {
    const starts = [];
    const contains = [];
    for (const e of group) {
      const name = fold(e.main);
      if (name.startsWith(q)) starts.push(e);
      else if (name.includes(q)) contains.push(e);
    }
    found.push(...starts, ...contains);
  }

  return found.slice(0, LIMIT);
}

/**
 * The best name for a detected point: the San José district or town whose
 * anchor it is nearest to.
 *
 * The old version only ever answered with one of the thirteen districts, so a
 * phone in Mountain View was told it was in Alviso. Districts and towns are
 * ranked together here and the nearer one wins, which puts a reader inside
 * San José in their district and a reader outside it in their own town.
 */
export function nameForPoint(point) {
  const candidates = [
    ...NEIGHBORHOODS.map((n) => ({ ...n, location: `${n.name}, San José` })),
    // San José itself is left out: its thirteen districts already stand for
    // it, and one anchor for a city this size would beat the district the
    // reader is actually standing in.
    ...CITIES.filter((c) => c.name !== "San José").map((c) => ({ ...c, location: c.name })),
  ];

  let best = null;
  for (const c of candidates) {
    // Squared degrees: this only has to rank candidates against each other,
    // and they are all within a few tenths of a degree of one another.
    const gap = (c.lat - point.lat) ** 2 + (c.lng - point.lng) ** 2;
    if (!best || gap < best.gap) best = { gap, location: c.location };
  }
  return best?.location ?? null;
}
