// Curated seed list — 25 public third spaces in San José.
// These stand in for the Google Places pull and are also the `manual_seed`
// rows the spec asks for. `google_place_id` is filled in once a real Places
// lookup runs; until then these carry the last known values.

export const CATEGORIES = ["Gathering", "Sport", "Service", "Other"];

export const INTEREST_GROUPS = [
  {
    name: "Sport & movement",
    items: ["Basketball", "Walking", "Soccer", "Swimming", "Pickleball", "Tennis"],
  },
  {
    name: "Making & learning",
    items: ["Reading", "Music", "Art & craft", "Tutoring", "Chess"],
  },
  {
    name: "Community",
    items: ["Volunteering", "Gardening", "Food & meals", "Faith groups", "Kids & family"],
  },
];

export const ALL_INTERESTS = INTEREST_GROUPS.flatMap((g) => g.items);

export const NEIGHBORHOODS = [
  { name: "Willow Glen", lat: 37.3069, lng: -121.8996 },
  { name: "Downtown", lat: 37.3352, lng: -121.8911 },
  { name: "Japantown", lat: 37.3489, lng: -121.8945 },
  { name: "East San José", lat: 37.3495, lng: -121.8291 },
  { name: "Almaden Valley", lat: 37.2358, lng: -121.8639 },
  { name: "Berryessa", lat: 37.3893, lng: -121.8586 },
  { name: "Alum Rock", lat: 37.3663, lng: -121.8235 },
];

export const PLACES = [
  {
    id: "roosevelt-community-center",
    name: "Roosevelt Community Center",
    category: "Gathering",
    address: "901 E Santa Clara St",
    lat: 37.3494,
    lng: -121.8763,
    rating: 4.6,
    reviews: 212,
    price_level: 0,
    popularity: 92,
    transit_minutes: 4,
    transit_line: "Bus 22",
    hours: "Open till 9",
    interests: ["Basketball", "Reading", "Volunteering", "Kids & family"],
    quote:
      "Open gym on Saturdays is packed and nobody minds if you're new. Staff are welcoming to all ages.",
  },
  {
    id: "mlk-library",
    name: "Dr. Martin Luther King Jr. Library",
    category: "Gathering",
    address: "150 E San Fernando St",
    lat: 37.3355,
    lng: -121.8845,
    rating: 4.6,
    reviews: 1840,
    price_level: 0,
    popularity: 88,
    transit_minutes: 3,
    transit_line: "VTA Light Rail",
    hours: "Open till 8",
    interests: ["Reading", "Tutoring", "Chess", "Art & craft"],
    quote: "Eight floors, quiet corners on every one of them, and the staff will find you anything.",
  },
  {
    id: "backesto-park",
    name: "Backesto Park courts",
    category: "Sport",
    address: "13th & Empire St",
    lat: 37.3529,
    lng: -121.893,
    rating: 4.3,
    reviews: 486,
    price_level: 0,
    popularity: 79,
    transit_minutes: 7,
    transit_line: "Bus 66",
    hours: "Open till dusk",
    interests: ["Basketball", "Tennis", "Walking", "Kids & family"],
    quote: "Pickup runs most evenings. Lights stay on late enough for a full game after work.",
  },
  {
    id: "emma-prusch-farm-park",
    name: "Emma Prusch Farm Park",
    category: "Service",
    address: "647 S King Rd",
    lat: 37.3378,
    lng: -121.8447,
    rating: 4.6,
    reviews: 2310,
    price_level: 0,
    popularity: 74,
    transit_minutes: 9,
    transit_line: "Bus 22",
    hours: "Open till sunset",
    interests: ["Gardening", "Volunteering", "Food & meals", "Kids & family"],
    quote: "Community garden plots, a barn, and volunteer days that actually need the help.",
  },
  {
    id: "willow-glen-library",
    name: "Willow Glen Library",
    category: "Gathering",
    address: "1157 Minnesota Ave",
    lat: 37.3062,
    lng: -121.8975,
    rating: 4.7,
    reviews: 268,
    price_level: 0,
    popularity: 71,
    transit_minutes: 6,
    transit_line: "Bus 61",
    hours: "Open till 6",
    interests: ["Reading", "Tutoring", "Kids & family"],
    quote: "Small, bright, and the story hour draws half the neighborhood.",
  },
  {
    id: "del-monte-park",
    name: "Del Monte Park",
    category: "Sport",
    address: "120 Lincoln Ave",
    lat: 37.313,
    lng: -121.9025,
    rating: 4.4,
    reviews: 322,
    price_level: 0,
    popularity: 66,
    transit_minutes: 8,
    transit_line: "Bus 63",
    hours: "Open till dusk",
    interests: ["Soccer", "Walking", "Kids & family"],
    quote: "Wide open field, shade at the edges, never so full you can't find a spot.",
  },
  {
    id: "bascom-community-center",
    name: "Bascom Community Center",
    category: "Gathering",
    address: "1000 S Bascom Ave",
    lat: 37.3153,
    lng: -121.9312,
    rating: 4.5,
    reviews: 197,
    price_level: 0,
    popularity: 76,
    transit_minutes: 5,
    transit_line: "Bus 25",
    hours: "Open till 9",
    interests: ["Basketball", "Art & craft", "Music", "Kids & family"],
    quote: "Classes for every age and a gym that's open when the classes aren't.",
  },
  {
    id: "guadalupe-river-park",
    name: "Guadalupe River Park",
    category: "Service",
    address: "438 Coleman Ave",
    lat: 37.3405,
    lng: -121.9016,
    rating: 4.3,
    reviews: 1120,
    price_level: 0,
    popularity: 69,
    transit_minutes: 6,
    transit_line: "VTA Light Rail",
    hours: "Open till sunset",
    interests: ["Walking", "Volunteering", "Gardening"],
    quote: "Monthly clean-ups are the easiest way to meet people who live here.",
  },
  {
    id: "olinder-park",
    name: "Olinder Park",
    category: "Sport",
    address: "848 E William St",
    lat: 37.3335,
    lng: -121.8686,
    rating: 4.0,
    reviews: 174,
    price_level: 0,
    popularity: 61,
    transit_minutes: 6,
    transit_line: "Bus 25",
    hours: "Open till dusk",
    interests: ["Basketball", "Soccer", "Kids & family"],
    quote: "Courts need work but the summer league still fills them every year.",
  },
  {
    id: "alum-rock-park",
    name: "Alum Rock Park",
    category: "Service",
    address: "15350 Penitencia Creek Rd",
    lat: 37.3959,
    lng: -121.8025,
    rating: 4.7,
    reviews: 3960,
    price_level: 1,
    popularity: 72,
    transit_minutes: 22,
    transit_line: "Bus 23 + walk",
    hours: "Open till sunset",
    interests: ["Walking", "Volunteering", "Kids & family"],
    quote: "Oldest park in California and the trail crews always want more hands.",
  },
  {
    id: "municipal-rose-garden",
    name: "Municipal Rose Garden",
    category: "Gathering",
    address: "1649 Naglee Ave",
    lat: 37.3316,
    lng: -121.926,
    rating: 4.8,
    reviews: 4210,
    price_level: 0,
    popularity: 68,
    transit_minutes: 11,
    transit_line: "Bus 23",
    hours: "Open till sunset",
    interests: ["Walking", "Gardening", "Art & craft"],
    quote: "Volunteers prune it every Wednesday morning and will hand you a pair of shears.",
  },
  {
    id: "japantown-jackson-st",
    name: "Japantown, Jackson Street",
    category: "Gathering",
    address: "Jackson St between 4th & 7th",
    lat: 37.3489,
    lng: -121.8945,
    rating: 4.7,
    reviews: 890,
    price_level: 2,
    popularity: 83,
    transit_minutes: 5,
    transit_line: "Bus 66",
    hours: "Market Sundays",
    interests: ["Food & meals", "Music", "Art & craft", "Faith groups"],
    quote: "Sunday market turns three blocks into one long conversation.",
  },
  {
    id: "almaden-community-center",
    name: "Almaden Community Center",
    category: "Gathering",
    address: "6445 Camden Ave",
    lat: 37.2447,
    lng: -121.8664,
    rating: 4.5,
    reviews: 143,
    price_level: 0,
    popularity: 64,
    transit_minutes: 14,
    transit_line: "Bus 64B",
    hours: "Open till 9",
    interests: ["Swimming", "Reading", "Kids & family", "Art & craft"],
    quote: "Pool, library, and a hall that hosts something nearly every night.",
  },
  {
    id: "camden-community-center",
    name: "Camden Community Center",
    category: "Gathering",
    address: "3369 Union Ave",
    lat: 37.2589,
    lng: -121.9247,
    rating: 4.4,
    reviews: 118,
    price_level: 1,
    popularity: 58,
    transit_minutes: 13,
    transit_line: "Bus 61",
    hours: "Open till 8",
    interests: ["Pickleball", "Art & craft", "Music"],
    quote: "Pickleball courts book out fast; drop-in hours are the quiet secret.",
  },
  {
    id: "seven-trees-community-center",
    name: "Seven Trees Community Center",
    category: "Gathering",
    address: "3590 Cas Dr",
    lat: 37.2861,
    lng: -121.8339,
    rating: 4.5,
    reviews: 231,
    price_level: 0,
    popularity: 70,
    transit_minutes: 10,
    transit_line: "Bus 68",
    hours: "Open till 9",
    interests: ["Basketball", "Tutoring", "Food & meals", "Kids & family"],
    quote: "Branch library on one side, gym on the other, free homework help between them.",
  },
  {
    id: "mayfair-community-center",
    name: "Mayfair Community Center",
    category: "Gathering",
    address: "2039 Kammerer Ave",
    lat: 37.3418,
    lng: -121.832,
    rating: 4.4,
    reviews: 96,
    price_level: 0,
    popularity: 67,
    transit_minutes: 8,
    transit_line: "Bus 22",
    hours: "Open till 8",
    interests: ["Volunteering", "Food & meals", "Music", "Kids & family"],
    quote: "The food distribution on Fridays runs on neighbors, not staff.",
  },
  {
    id: "berryessa-library",
    name: "Berryessa Branch Library",
    category: "Gathering",
    address: "3355 Noble Ave",
    lat: 37.3903,
    lng: -121.8617,
    rating: 4.6,
    reviews: 412,
    price_level: 0,
    popularity: 73,
    transit_minutes: 9,
    transit_line: "Bus 61",
    hours: "Open till 8",
    interests: ["Reading", "Tutoring", "Chess"],
    quote: "Study rooms you can actually get, and a chess club on Thursdays.",
  },
  {
    id: "educational-park-library",
    name: "Educational Park Library",
    category: "Gathering",
    address: "1772 Educational Park Dr",
    lat: 37.3673,
    lng: -121.839,
    rating: 4.5,
    reviews: 187,
    price_level: 0,
    popularity: 60,
    transit_minutes: 12,
    transit_line: "Bus 77",
    hours: "Open till 6",
    interests: ["Reading", "Tutoring"],
    quote: "Shares a campus with the high school, so afternoons are lively.",
  },
  {
    id: "hillview-library",
    name: "Hillview Branch Library",
    category: "Gathering",
    address: "1600 Hopkins Dr",
    lat: 37.3436,
    lng: -121.8296,
    rating: 4.5,
    reviews: 224,
    price_level: 0,
    popularity: 65,
    transit_minutes: 7,
    transit_line: "Bus 22",
    hours: "Open till 8",
    interests: ["Reading", "Tutoring", "Kids & family"],
    quote: "Newest branch on the east side and it shows — light, quiet, welcoming.",
  },
  {
    id: "watson-park",
    name: "Watson Park",
    category: "Sport",
    address: "22nd & E Jackson St",
    lat: 37.3536,
    lng: -121.8817,
    rating: 4.2,
    reviews: 208,
    price_level: 0,
    popularity: 57,
    transit_minutes: 8,
    transit_line: "Bus 66",
    hours: "Open till dusk",
    interests: ["Soccer", "Walking", "Kids & family"],
    quote: "Reopened after a long cleanup. Big lawns, new playground, room to run.",
  },
  {
    id: "lake-cunningham-park",
    name: "Lake Cunningham Park",
    category: "Sport",
    address: "2305 S White Rd",
    lat: 37.3325,
    lng: -121.8085,
    rating: 4.5,
    reviews: 2680,
    price_level: 1,
    popularity: 75,
    transit_minutes: 16,
    transit_line: "Bus 70",
    hours: "Open till sunset",
    interests: ["Swimming", "Walking", "Kids & family", "Basketball"],
    quote: "Skate park, lake loop, and enough space that it never feels crowded.",
  },
  {
    id: "kelley-park",
    name: "Kelley Park",
    category: "Service",
    address: "1300 Senter Rd",
    lat: 37.3197,
    lng: -121.862,
    rating: 4.6,
    reviews: 1490,
    price_level: 1,
    popularity: 70,
    transit_minutes: 11,
    transit_line: "Bus 25",
    hours: "Open till sunset",
    interests: ["Gardening", "Volunteering", "Kids & family", "Food & meals"],
    quote: "The Japanese Friendship Garden alone is worth the trip; docents are volunteers.",
  },
  {
    id: "st-james-park",
    name: "St. James Park",
    category: "Gathering",
    address: "N 2nd St & E St James St",
    lat: 37.3383,
    lng: -121.8905,
    rating: 3.9,
    reviews: 640,
    price_level: 0,
    popularity: 62,
    transit_minutes: 2,
    transit_line: "VTA Light Rail",
    hours: "Open till dusk",
    interests: ["Walking", "Music", "Chess"],
    quote: "Free concerts in summer and a light rail stop on the corner.",
  },
  {
    id: "plaza-de-cesar-chavez",
    name: "Plaza de César Chávez",
    category: "Gathering",
    address: "194 S Market St",
    lat: 37.3327,
    lng: -121.889,
    rating: 4.4,
    reviews: 1310,
    price_level: 0,
    popularity: 81,
    transit_minutes: 2,
    transit_line: "VTA Light Rail",
    hours: "Open till 10",
    interests: ["Music", "Food & meals", "Walking", "Art & craft"],
    quote: "Fountains in summer, ice rink in winter, always somebody there.",
  },
  {
    id: "grace-community-center",
    name: "Grace Community Center",
    category: "Service",
    address: "484 E San Fernando St",
    lat: 37.335,
    lng: -121.879,
    rating: 4.7,
    reviews: 88,
    price_level: 0,
    popularity: 63,
    transit_minutes: 5,
    transit_line: "Bus 22",
    hours: "Open till 6",
    interests: ["Volunteering", "Food & meals", "Faith groups", "Tutoring"],
    quote: "Meal service every weekday and they will put you to work the day you show up.",
  },
  {
    // Google marked this one permanently closed. It stays reachable by link
    // but never counts toward a score or appears on the map.
    id: "bascom-rec-room",
    name: "Bascom Rec Room",
    category: "Gathering",
    address: "1490 S Bascom Ave",
    lat: 37.3106,
    lng: -121.9316,
    rating: 4.1,
    reviews: 64,
    price_level: 0,
    popularity: 40,
    transit_minutes: 6,
    transit_line: "Bus 25",
    hours: "—",
    interests: ["Basketball", "Music"],
    quote: null,
    closed: true,
    closed_on: "4 August",
  },
];

// Adopt-a-third-space: funding requests. Display only — no payment flow.
export const APPLICANTS = [
  {
    id: "olinder-courts",
    name: "Olinder Park basketball courts",
    category: "Sport",
    neighborhood: "East San José",
    lat: 37.3335,
    lng: -121.8686,
    ask: 14000,
    reach: 600,
    need: 88,
    filed: "12 Jun",
    summary:
      "Resurfacing and two new hoops. Ask: $14,000. Serves ~600 residents within a half mile.",
    detail:
      "Two of four hoops are missing rims and the surface floods after rain. The neighborhood association wants resurfacing, two hoops, and a drinking fountain, so the courts can host the summer league again.",
    signals: [
      { label: "Residents within ½ mile", value: "High" },
      { label: "Existing free spaces nearby", value: "Only 1", warn: true },
      { label: "Transit access", value: "Bus 25, 6 min" },
    ],
    contact: "olinder.assoc@example.org",
  },
  {
    id: "alum-rock-reading-room",
    name: "Alum Rock reading room",
    category: "Gathering",
    neighborhood: "Alum Rock",
    lat: 37.3663,
    lng: -121.8235,
    ask: 6200,
    reach: 380,
    need: 81,
    filed: "2 Jul",
    summary:
      "Evening hours for a volunteer-run study space. Ask: $6,200 for staffing through spring.",
    detail:
      "The room is donated and the volunteers are already there. What's missing is a paid coordinator two evenings a week so the space can stay open past six, when students actually need it.",
    signals: [
      { label: "Students within ½ mile", value: "High" },
      { label: "Existing free spaces nearby", value: "Only 2", warn: true },
      { label: "Transit access", value: "Bus 23, 4 min" },
    ],
    contact: "alumrock.reading@example.org",
  },
  {
    id: "guadalupe-cleanup-hub",
    name: "Guadalupe River clean-up hub",
    category: "Service",
    neighborhood: "Downtown",
    lat: 37.3405,
    lng: -121.9016,
    ask: 3400,
    reach: 240,
    need: 74,
    filed: "28 Jul",
    summary: "Tool shed and water station for monthly volunteer days. Ask: $3,400.",
    detail:
      "Volunteers currently haul rakes and water in from their own cars each month. A locked shed and a plumbed water station at the trailhead would roughly double the number of people who stay past an hour.",
    signals: [
      { label: "Volunteer turnout, monthly", value: "Growing" },
      { label: "On-site storage", value: "None", warn: true },
      { label: "Transit access", value: "Light rail, 5 min" },
    ],
    contact: "guadalupe.volunteers@example.org",
  },
];
