// The catalogue, and the vocabulary the interface is built from.
//
// Nothing describing a place is written by hand any more. `catalogue.json` is
// generated by `scripts/sync-sanjose.mjs` straight from the City of San José's
// open data service — parks, community centers, libraries, what amenities are
// actually on the ground, the city's own 2025 park condition assessments, and
// the Equity Index tracts behind the invest list. Ratings, review counts, and
// quotes are layered on afterwards by `scripts/refresh-places.mjs` from Google.
//
// Re-generate rather than edit:
//
//   node scripts/sync-sanjose.mjs
//
// The lists below are the app's own vocabulary — the words the filter chips
// and the interest picker are written in. They are interface copy, not claims
// about any particular place.

import catalogue from "./catalogue.json";

export const CATEGORIES = ["Gathering", "Sport", "Service", "Other"];

export const INTEREST_GROUPS = [
  {
    name: "Sport & movement",
    items: ["Basketball", "Walking", "Soccer", "Swimming", "Pickleball", "Tennis"],
  },
  {
    name: "Making & learning",
    items: ["Reading", "Music", "Art & craft", "Tutoring", "Chess"],
  },
  {
    name: "Community",
    items: ["Volunteering", "Gardening", "Food & meals", "Faith groups", "Kids & family"],
  },
];

export const ALL_INTERESTS = INTEREST_GROUPS.flatMap((g) => g.items);

/** When the catalogue was last pulled from the city, for the about line. */
export const GENERATED = catalogue.generated;

export const SOURCE = catalogue.source;

/**
 * The city's own planning areas — Willow Glen, Almaden, Alum Rock and the
 * dozen others — ordered by how many third spaces sit in each. The profiler
 * falls back to these when Google's autocomplete is unreachable.
 *
 * Deliberately the coarse geography, not the 297-entry Neighborhoods layer:
 * that one is accurate on a place ("Northside-Backesto") but unhelpful in a
 * "where are you?" picker. A place carries both — `neighborhood` is the
 * specific one, `district` the recognisable one.
 */
export const NEIGHBORHOODS = catalogue.neighborhoods;

export const PLACES = catalogue.places;

/**
 * Where the city's own numbers say investment is most needed: a poor 2025
 * condition assessment inside a high-priority Equity Index tract. Every field
 * on a row is published by the city and shown on the screen, so the ranking
 * can be checked rather than taken on trust.
 */
export const NEEDS = catalogue.needs;
