// Seed list — 26 public third spaces in San José.
//
// Every row carries a real `google_place_id`, so the app looks a place up
// rather than searching for it. `name`, `address`, `lat`, `lng`, `rating`,
// `reviews`, `summary`, and `quote` are all written by
// `scripts/refresh-places.mjs` straight from that listing — re-run it to
// refresh them, and never edit them by hand. `summary` is composed from the
// facts Google reports (see src/lib/describe.js) and `quote` is one real
// review, verbatim, with its author.
//
// Still hand-set, and the one thing here that is not measured: `popularity`,
// `transit_minutes`, `transit_line`, `hours`, `interests`, and `category`.
// Google's free APIs expose no busy-times signal, so `popularity` is an
// estimate rather than data.

export const CATEGORIES = ["Gathering", "Sport", "Service", "Other"];

export const INTEREST_GROUPS = [
  {
    name: "Sport & movement",
    items: ["Basketball", "Walking", "Soccer", "Swimming", "Pickleball", "Tennis"],
  },
  {
    name: "Making & learning",
    items: ["Reading", "Music", "Art & craft", "Tutoring", "Chess"],
  },
  {
    name: "Community",
    items: ["Volunteering", "Gardening", "Food & meals", "Faith groups", "Kids & family"],
  },
];

export const ALL_INTERESTS = INTEREST_GROUPS.flatMap((g) => g.items);

export const NEIGHBORHOODS = [
  { name: "Willow Glen", lat: 37.3069, lng: -121.8996 },
  { name: "Downtown", lat: 37.3352, lng: -121.8911 },
  { name: "Japantown", lat: 37.3489, lng: -121.8945 },
  { name: "East San José", lat: 37.3495, lng: -121.8291 },
  { name: "Almaden Valley", lat: 37.2358, lng: -121.8639 },
  { name: "Berryessa", lat: 37.3893, lng: -121.8586 },
  { name: "Alum Rock", lat: 37.3663, lng: -121.8235 },
];

export const PLACES = [
  {
    id: "roosevelt-community-center",
    google_place_id: "ChIJE9jUwunMj4ARkSFRHk2X1t8",
    name: "Roosevelt Community Center",
    category: "Gathering",
    address: "901 E Santa Clara St",
    lat: 37.345473,
    lng: -121.871858,
    rating: 4.3,
    reviews: 218,
    price_level: 0,
    popularity: 92,
    transit_minutes: 4,
    transit_line: "Bus 22",
    hours: "Open till 9",
    interests: ["Basketball", "Reading", "Volunteering", "Kids & family"],
    summary:
      "Community Center with event space · restrooms, free parking, and step-free entrance.",
    quote:
      "First off, while the navigation takes you to the front of the community center entrance, this is not where you want to be. You want to park in the back lot and enter from the back entrance.\n\nThe community center is good size and has an inviting setup though the front entrance has homeless folks and a lot of chaos.\n\nThe event we attended had food catered and looks like the area is able to hold about 150 ish people.",
    quote_author: "Rahul Somani",
    quote_rating: 4,
  },
  {
    id: "mlk-library",
    google_place_id: "ChIJgbAiC7zMj4ARf9VjyD-BcOM",
    name: "Dr. Martin Luther King, Jr. Library",
    category: "Gathering",
    address: "150 E San Fernando St",
    lat: 37.335482,
    lng: -121.884999,
    rating: 4.4,
    reviews: 531,
    price_level: 0,
    popularity: 88,
    transit_minutes: 3,
    transit_line: "VTA Light Rail",
    hours: "Open till 8",
    interests: ["Reading", "Tutoring", "Chess", "Art & craft"],
    summary: "Library · free parking and step-free entrance.",
    quote:
      "A humongous library in the heart of San Jose. I think there were like, 8 floors? Which is even more than the San Francisco Main Library! There is endless study space and an infinite catalogue of books. It really feels like a center for everything, as you can also find programs,  events, collections, and showcases here. I really liked their California collection! I think the library doubles as the college library for San Jose State, too, so there are some student resources and spaces.\n\nThe building is really beautiful, and the view gets better the higher you go.\n\nThe main reason I docked a star from the MLK Library is because I think it could be better maintained. Some floors were great, but other floors were awkwardly furnished and had missing chairs, broken outlets, empty bookshelves, and even spills and messes.\n\nOther than that, it’s a near-perfect library. Overall, 4/5.",
    quote_author: "Hana Estalilla",
    quote_rating: 4,
  },
  {
    id: "backesto-park",
    google_place_id: "ChIJTb2U2Y3Mj4ARz4g0qvQkriE",
    name: "Backesto Park",
    category: "Sport",
    address: "551 N 13th St",
    lat: 37.352257,
    lng: -121.884503,
    rating: 4.2,
    reviews: 1111,
    price_level: 0,
    popularity: 79,
    transit_minutes: 7,
    transit_line: "Bus 66",
    hours: "Open till dusk",
    interests: ["Basketball", "Tennis", "Walking", "Kids & family"],
    summary:
      "Standard park offering spacious lawns plus a playground, sports fields, courts & a 1920s fountain.",
    quote:
      "I visited this park for a tennis match and was pleasantly surprised by its size and the number of people present. Located in a residential area, the park saw a surge in visitors as the sun set. They have a BBQ area that’s pet-friendly, which is a great addition. The tennis courts are well-maintained, but they don’t compare to the best courts I’ve played on. There are restroom facilities and other sports amenities available. There’s ample parking around the park, making it convenient for visitors.",
    quote_author: "Jagadeesh Rahul",
    quote_rating: 4,
  },
  {
    id: "emma-prusch-farm-park",
    google_place_id: "ChIJrytoZyXNj4AR8BLmODffC7I",
    name: "Emma Prusch Farm Park",
    category: "Service",
    address: "647 S King Rd",
    lat: 37.339996,
    lng: -121.845524,
    rating: 4.6,
    reviews: 2768,
    price_level: 0,
    popularity: 74,
    transit_minutes: 9,
    transit_line: "Bus 22",
    hours: "Open till sunset",
    interests: ["Gardening", "Volunteering", "Food & meals", "Kids & family"],
    summary:
      "Compact community farm features heirloom vegetable gardens, orchards, chickens & a fair.",
    quote:
      "Best place for hanging out with your kids and family on the weekends.\nTons of space, playgrounds for kids and picnic area. The place also have a small zoo but I never see animals inside this park.\nDefinitely will be my frequent visit destination",
    quote_author: "The Rice Field Man",
    quote_rating: 5,
  },
  {
    id: "willow-glen-library",
    google_place_id: "ChIJqxLnzFgzjoARojjJwYYgy_s",
    name: "Willow Glen Branch Library",
    category: "Gathering",
    address: "1157 Minnesota Ave",
    lat: 37.302941,
    lng: -121.900062,
    rating: 4.6,
    reviews: 123,
    price_level: 0,
    popularity: 71,
    transit_minutes: 6,
    transit_line: "Bus 61",
    hours: "Open till 6",
    interests: ["Reading", "Tutoring", "Kids & family"],
    summary: "Library · free parking and step-free entrance.",
    quote:
      "Such a nice and well-maintained library! They have a wide selection of books for both children and teens. The reading spaces are clean, organized, and very inviting. I also love that they have a play area for toddlers. The staff are friendly and accommodating. Will definitely visit again when I’m back! 📚✨",
    quote_author: "BA",
    quote_rating: 5,
  },
  {
    id: "del-monte-park",
    google_place_id: "ChIJJZ6y2lXLj4AR54sIIVIYQ2U",
    name: "Del Monte Park",
    category: "Sport",
    address: "806 W Home St",
    lat: 37.320634,
    lng: -121.905157,
    rating: 4.5,
    reviews: 819,
    price_level: 0,
    popularity: 66,
    transit_minutes: 8,
    transit_line: "Bus 63",
    hours: "Open till dusk",
    interests: ["Soccer", "Walking", "Kids & family"],
    summary: "Park · good for kids, free parking, and step-free entrance.",
    quote:
      "A very good park and sports field for all age of people.  Centrally located in downtown.  A devoted picnic area is provided. Separate parks for small and large dogs.  Soccer grounds are full size and well maintained.  Restrooms are adjacent to the park. Wheelchair accessible entrance.",
    quote_author: "Arjun Gargava",
    quote_rating: 5,
  },
  {
    id: "bascom-community-center",
    google_place_id: "ChIJ49yBtMw0joAR8l80thlC3Ts",
    name: "Bascom Community Center",
    category: "Gathering",
    address: "1000 S Bascom Ave",
    lat: 37.3075,
    lng: -121.931167,
    rating: 4.5,
    reviews: 165,
    price_level: 0,
    popularity: 76,
    transit_minutes: 5,
    transit_line: "Bus 25",
    hours: "Open till 9",
    interests: ["Basketball", "Art & craft", "Music", "Kids & family"],
    summary:
      "Community Center with event space · restrooms, free parking, and step-free entrance.",
    quote:
      "Great place with library, basketball courts, and cafe. Someone can spend the whole day there with reading, working, working out. I spotted a rainbow right next to it once day!",
    quote_author: "Upma Sharma",
    quote_rating: 5,
  },
  {
    id: "guadalupe-river-park",
    google_place_id: "ChIJAbdJa2LLj4ARkimX9gu_Edg",
    name: "Guadalupe River Park",
    category: "Service",
    address: "438 Coleman Ave",
    lat: 37.343308,
    lng: -121.903438,
    rating: 4,
    reviews: 1640,
    price_level: 0,
    popularity: 69,
    transit_minutes: 6,
    transit_line: "VTA Light Rail",
    hours: "Open till sunset",
    interests: ["Walking", "Volunteering", "Gardening"],
    summary:
      "Small city park offering a visitor's center, a playground, a community garden & 2.6 miles of trails.",
    quote:
      "This Guadalupe River Park can definitely use some maintenance!!!! This park is about 120 acre on the banks of the Guadalupe River that stretches along 2.5 miles in the downtown area. It is surrounded by many Tall buildings, various businesses, and many other Historical Shops/Restaurants. A short distance from the popular San Pedro Square Market, Sap Center, Heritage Rose Garden, Discovery Meadow, and Plaza De Cesar Chavez. There are walking Trails, Tennis Courts, bike paths, playgrounds, Shades, Bridges, Benches, Restrooms, and it’s a Dogs-Friendly Environments for the public. I’m sure glad I came here on a perfect peaceful evening where the views are radiants and beautiful!!!\nA Lovely day right before sunset!!!! I definitely wouldn’t want to be walking around here after dark. Too Creepy!!!!! September11, 2025",
    quote_author: "Thia Le",
    quote_rating: 4,
  },
  {
    id: "olinder-park",
    google_place_id: "ChIJqyvKtNHMj4ARJm0cSFLXe4U",
    name: "Selma Olinder Park",
    category: "Sport",
    address: "1117 Woodborough Dr",
    lat: 37.334175,
    lng: -121.866102,
    rating: 4.2,
    reviews: 315,
    price_level: 0,
    popularity: 61,
    transit_minutes: 6,
    transit_line: "Bus 25",
    hours: "Open till dusk",
    interests: ["Basketball", "Soccer", "Kids & family"],
    summary:
      "13-acre city park featuring athletic fields, picnic sites, BBQs & separate small & large dog parks.",
    quote:
      "If you're looking for a great park to visit with your family, Selma Olinder Park is definitely worth checking out. This beautiful park has a lot to offer, including a spacious playground area that is perfect for children.\n\nAside from the playground, Selma Olinder Park is a great place to take a walk or enjoy a picnic. The park  features plenty of green space, as well as benches and tables for visitors to use. There are also several paths that wind through the park, providing a great opportunity for exercise and exploring.\n\nHowever, it's worth noting that there is an ever-present homeless danger along the Coyote Creek Trail, which runs adjacent to the park. While the park itself is safe and well-monitored, visitors should take caution and be aware of their surroundings if using the trail.",
    quote_author: "Miguel “shadowmarrba” Rivas",
    quote_rating: 4,
  },
  {
    id: "alum-rock-park",
    google_place_id: "ChIJ-ZogKrvMj4ARKrML-5D1a88",
    name: "Alum Rock Park",
    category: "Service",
    address: "15350 Penitencia Creek Rd",
    lat: 37.395408,
    lng: -121.825311,
    rating: 4.7,
    reviews: 3614,
    price_level: 1,
    popularity: 72,
    transit_minutes: 22,
    transit_line: "Bus 23 + walk",
    hours: "Open till sunset",
    interests: ["Walking", "Volunteering", "Kids & family"],
    summary:
      "Spacious park featuring hiking & biking trails, mineral springs & several picnic areas.",
    quote:
      "⭐⭐⭐⭐⭐\n\nAlum Rock Park is a hidden gem in San Jose and the perfect escape into nature without leaving the city. One of California's oldest municipal parks, it offers beautiful tree-lined trails, peaceful streams, scenic canyon views, and plenty of shaded picnic spots. Alum Rock Park is known for its rich history, diverse hiking trails, and natural beauty.\n\nWe thoroughly enjoyed our visit, especially the tranquil atmosphere and the chance to connect with nature. The well-maintained trails are suitable for families as well as avid hikers, and there are several spots to simply sit back and enjoy the surroundings. If you're looking for a peaceful getaway, a morning hike, or a family picnic, Alum Rock Park is an excellent choice. It's a place you'll want to visit again and again.",
    quote_author: "Hemanth Shriyan",
    quote_rating: 5,
  },
  {
    id: "municipal-rose-garden",
    google_place_id: "ChIJb5KWbRTLj4AR1iYBl5vpNf8",
    name: "Municipal Rose Garden",
    category: "Gathering",
    address: "1649 Naglee Ave",
    lat: 37.331881,
    lng: -121.928612,
    rating: 4.7,
    reviews: 7894,
    price_level: 0,
    popularity: 68,
    transit_minutes: 11,
    transit_line: "Bus 23",
    hours: "Open till sunset",
    interests: ["Walking", "Gardening", "Art & craft"],
    summary:
      "180+ rose varieties typically blooming April-November in a colorful 5.5-acre garden with a fountain.",
    quote:
      "I honestly didn’t expect anything extraordinary when we were heading to the Rose Garden in San Jose, but the moment we arrived, I was completely amazed. Seeing all the beautiful roses, the incredible variety of colors, and the perfectly maintained landscape was absolutely breathtaking.\n\nThis place is truly magical and feels like a hidden gem. If you are visiting Santa Rosa, you absolutely have to come here during rose blooming season. The beauty, the atmosphere, and the attention to detail make it a truly unforgettable experience. A definite “wow” moment! 🌹",
    quote_author: "Mary B",
    quote_rating: 5,
  },
  {
    id: "japantown-jackson-st",
    google_place_id: "ChIJzcQR0IPMj4ARssG9NdP7_qU",
    name: "Japantown",
    category: "Gathering",
    address: "Jackson St between 4th & 7th",
    lat: 37.349462,
    lng: -121.89397,
    rating: null,
    reviews: 0,
    price_level: 2,
    popularity: 83,
    transit_minutes: 5,
    transit_line: "Bus 66",
    hours: "Market Sundays",
    interests: ["Food & meals", "Music", "Art & craft", "Faith groups"],
    summary: null,
    quote: null,
    quote_author: null,
    quote_rating: null,
  },
  {
    id: "almaden-community-center",
    google_place_id: "ChIJpaYDGRAxjoARJYG1GyObzyY",
    name: "Almaden Community Center",
    category: "Gathering",
    address: "6445 Camden Ave",
    lat: 37.221698,
    lng: -121.869309,
    rating: 4.8,
    reviews: 84,
    price_level: 0,
    popularity: 64,
    transit_minutes: 14,
    transit_line: "Bus 64B",
    hours: "Open till 9",
    interests: ["Reading", "Kids & family", "Art & craft"],
    summary: "Community Center with event space · restrooms and step-free entrance.",
    quote:
      "Dropped in for Saturday morning table tennis. 8 tables, skilled players playing mostly doubles.\nSpent five hours, met a lot of new friends and had a great experience.",
    quote_author: "Peter Thelin",
    quote_rating: 5,
  },
  {
    id: "camden-community-center",
    google_place_id: "ChIJj-5R5ls0joARzerKtwWlULo",
    name: "Camden Community Center",
    category: "Gathering",
    address: "3369 Union Ave",
    lat: 37.263634,
    lng: -121.93338,
    rating: 4.5,
    reviews: 402,
    price_level: 1,
    popularity: 58,
    transit_minutes: 13,
    transit_line: "Bus 61",
    hours: "Open till 8",
    interests: ["Swimming", "Pickleball", "Art & craft", "Music"],
    summary:
      "Community Center with a pool, an auditorium, and event space · restrooms and step-free entrance.",
    quote:
      "Best public pool in south San Jose area.  Beautiful 8 lanes 25 yards modern, no gutter pool.  Swam there a Friday evening, open from 4:30pm until 8pm.  Not crowded at all, and super cheap drop in fee.  Only complaint is water temperature, which is too warm.  Facilities for changing and showering are clean and sufficient.  Too bad there is no early morning swimming, or noon swimming.",
    quote_author: "Soren Soe",
    quote_rating: 5,
  },
  {
    id: "seven-trees-community-center",
    google_place_id: "ChIJCSCY_GkyjoARC4nPDjhlP9c",
    name: "Seven Trees Community Center",
    category: "Gathering",
    address: "3590 Cas Dr",
    lat: 37.284856,
    lng: -121.833699,
    rating: 4.5,
    reviews: 45,
    price_level: 0,
    popularity: 70,
    transit_minutes: 10,
    transit_line: "Bus 68",
    hours: "Open till 9",
    interests: ["Basketball", "Tutoring", "Food & meals", "Kids & family"],
    summary:
      "Community Center with a gym, an auditorium, and event space · restrooms and step-free entrance.",
    quote:
      "Seven Trees Community centre is Best and well facilitated Community centre.\nI've never been to a community center before, but I discovered that this one has a library, exercise room, gym, and several multi use rooms. In addition to that there is a county sponsored senior nutrition program that has free lunch for seniors (or they can donate $3 to support the volunteer run program).\nIf you come with a senior it is only $8 for non-seniors.\nThe warm colors and angles of this building are really interesting, and it is LEEDS certified to be energy efficient. There is ample parking and an outdoor play area for kids.\nA great community resource for kids, adults and seniors.",
    quote_author: "PRAJA PRAKASH JADAWALA",
    quote_rating: 5,
  },
  {
    id: "mayfair-community-center",
    google_place_id: "ChIJhRnNKD3Nj4ARn14BnpSipUA",
    name: "Mayfair Community Center",
    category: "Gathering",
    address: "2039 Kammerer Ave",
    lat: 37.351514,
    lng: -121.843816,
    rating: 4.5,
    reviews: 155,
    price_level: 0,
    popularity: 67,
    transit_minutes: 8,
    transit_line: "Bus 22",
    hours: "Open till 8",
    interests: ["Volunteering", "Food & meals", "Music", "Kids & family"],
    summary: "Community Center with event space · restrooms and step-free entrance.",
    quote: "Love the maker Center. Been going there since I was a child",
    quote_author: "Shirlene Burns",
    quote_rating: 4,
  },
  {
    id: "berryessa-library",
    google_place_id: "ChIJRUOyYpXNj4AR2iSjcJvg4Fo",
    name: "Berryessa Branch Library",
    category: "Gathering",
    address: "3355 Noble Ave",
    lat: 37.393948,
    lng: -121.840794,
    rating: 4.7,
    reviews: 164,
    price_level: 0,
    popularity: 73,
    transit_minutes: 9,
    transit_line: "Bus 61",
    hours: "Open till 8",
    interests: ["Reading", "Tutoring", "Chess"],
    summary: "Library · free parking and step-free entrance.",
    quote:
      "Ample space for children to play and read books. Good collection of children’s book. Dedicated restrooms for families.\nThere is a playground just outside the library, which is great as kids get both indoor and outdoor time in a trip to this library.",
    quote_author: "Nikhil Singhal",
    quote_rating: 5,
  },
  {
    id: "educational-park-library",
    google_place_id: "ChIJs8FINP7Mj4ARTIb7E8jrPsk",
    name: "Educational Park Branch Library",
    category: "Gathering",
    address: "1772 Educational Park Dr",
    lat: 37.365631,
    lng: -121.857667,
    rating: 4.3,
    reviews: 82,
    price_level: 0,
    popularity: 60,
    transit_minutes: 12,
    transit_line: "Bus 77",
    hours: "Open till 6",
    interests: ["Reading", "Tutoring"],
    summary: "Library · free parking and step-free entrance.",
    quote:
      "Its situated beautifully, tucked back away from what feels like the \"chaos\" in life. Huge parking lot not much shade but lots of big trees strategically planted to separate the location from that \"chaos\" that is life. I havent even gone in yet and im already sold and they aren't charging late fines anymore so I dont have to keep looking over my shoulder and hiding out. I learned my lesson that summer, never, ever check out books for the summer its just too long and the odds increase that your gonna probably accidently put it in the donation box by accident.",
    quote_author: "Theresa “Tessa” La Voun",
    quote_rating: 5,
  },
  {
    id: "hillview-library",
    google_place_id: "ChIJ8YZy0krNj4AR3Jm9qQTtZgA",
    name: "Hillview Branch Library",
    category: "Gathering",
    address: "1600 Hopkins Dr",
    lat: 37.337804,
    lng: -121.831147,
    rating: 4.4,
    reviews: 72,
    price_level: 0,
    popularity: 65,
    transit_minutes: 7,
    transit_line: "Bus 22",
    hours: "Open till 8",
    interests: ["Reading", "Tutoring", "Kids & family"],
    summary: "Library · free parking and step-free entrance.",
    quote:
      "This is one of my favorite libraries. I've been here a few times because my friends live by here; we have some meetings and study sessions. The kids love it, too. There are computers that you can use here if you don't have your own. The ambiance is chill and the employees are kind. I love the layout of the building. There are quiet rooms you can reserve to study in. There are great books here and I can always reserve some from other libraries in San Jose and have them sent here.",
    quote_author: "Nora Ismail",
    quote_rating: 5,
  },
  {
    id: "watson-park",
    google_place_id: "ChIJ35Ir9_TMj4ARAIanMkLhgfY",
    name: "Watson Park",
    category: "Sport",
    address: "N 22nd St & Jackson St",
    lat: 37.359563,
    lng: -121.875433,
    rating: 4.2,
    reviews: 815,
    price_level: 0,
    popularity: 57,
    transit_minutes: 8,
    transit_line: "Bus 66",
    hours: "Open till dusk",
    interests: ["Soccer", "Walking", "Kids & family"],
    summary:
      "27-acre green space with toddler & big kid playgrounds, multi-use fields & an off-leash dog park.",
    quote:
      "Nice playground. Beautiful soccer fields. Even has a dog park way in the corner, but didn't visit it because there were so many dogs even in the middle of the day. My only problem is the large field near the playground and courts were not maintained and covered in long weeds.",
    quote_author: "Christina Kulkarni",
    quote_rating: 4,
  },
  {
    id: "lake-cunningham-park",
    google_place_id: "ChIJdR_EjVotjoARXqra-Sgdi4k",
    name: "Lake Cunningham Regional Park",
    category: "Sport",
    address: "2305 S White Rd",
    lat: 37.337271,
    lng: -121.808674,
    rating: 4.5,
    reviews: 987,
    price_level: 1,
    popularity: 75,
    transit_minutes: 16,
    transit_line: "Bus 70",
    hours: "Open till sunset",
    interests: ["Swimming", "Walking", "Kids & family", "Basketball"],
    summary:
      "Park with sports fields · good for kids, free parking, and step-free entrance.",
    quote:
      "Lake Cunningham Regional Park is one of the best parks I’ve visited in the San Jose area. The park is incredibly spacious, clean, and well maintained, making it a great destination for families, couples, fitness enthusiasts, and anyone looking to spend time outdoors. The walking and biking trails are wide, scenic, and perfect for a relaxing stroll or an energetic workout while enjoying beautiful views of the lake.\n\nOne of my favorite features is how much there is to do. The playgrounds are fantastic for children, and there are plenty of open grassy areas for picnics, sports, or simply relaxing in the sunshine. The lake creates a peaceful atmosphere, and it’s a wonderful place to watch birds, take photos, or unwind after a busy day. There are also plenty of benches and shaded spots throughout the park, making it comfortable even during warmer weather.\n\nThe park feels safe and welcoming, with ample parking and clean restroom facilities. Whether you’re visiting for a morning walk, an afternoon with family, or just to enjoy nature, there’s something here for everyone. I was impressed by how well everything is maintained and how enjoyable the overall experience was.\n\nIf you’re in San Jose or the surrounding area, I highly recommend spending a few hours at Lake Cunningham Regional Park. It’s a beautiful place to exercise, relax, and appreciate the outdoors. I’ll definitely be coming back and would happily recommend it to friends and family looking for a peaceful and enjoyable park experience.",
    quote_author: "MN",
    quote_rating: 5,
  },
  {
    id: "kelley-park",
    google_place_id: "ChIJnwKWPCwzjoARmYIzOuWZLuk",
    name: "Kelley Park",
    category: "Service",
    address: "1300 Senter Rd",
    lat: 37.322822,
    lng: -121.858128,
    rating: 4.4,
    reviews: 3079,
    price_level: 1,
    popularity: 70,
    transit_minutes: 11,
    transit_line: "Bus 25",
    hours: "Open till sunset",
    interests: ["Gardening", "Volunteering", "Kids & family", "Food & meals"],
    summary:
      "This park, which contains a zoo & living history museum, offers picnic spots & lawn bowling greens.",
    quote:
      "My 4 year old enjoyed the San Jose zoo. There's a petting farm where you can comb the goats. There's multiple toddler rides for the kids. Its a playland for young children.",
    quote_author: "Peter Vong",
    quote_rating: 4,
  },
  {
    id: "st-james-park",
    google_place_id: "ChIJU_8CCJjMj4ARfFaS4nEundw",
    name: "St James Park",
    category: "Gathering",
    address: "N 2nd St & E St James St",
    lat: 37.33889,
    lng: -121.891157,
    rating: 3.5,
    reviews: 1434,
    price_level: 0,
    popularity: 62,
    transit_minutes: 2,
    transit_line: "VTA Light Rail",
    hours: "Open till dusk",
    interests: ["Walking", "Music", "Chess"],
    summary:
      "6.8-acre city park, featuring playgrounds, picnic facilities & an exercise course.",
    quote:
      "Decent spot if you’re nearby and want to take a break. There are benches and open areas, but it doesn’t always feel the safest depending on the time of day.",
    quote_author: "Katherine Turner",
    quote_rating: 4,
  },
  {
    id: "plaza-de-cesar-chavez",
    google_place_id: "ChIJkTeUJ7vMj4ARXZyxTRC6iOc",
    name: "Plaza de Cesar Chavez",
    category: "Gathering",
    address: "1 Paseo de San Antonio",
    lat: 37.332486,
    lng: -121.889842,
    rating: 4.4,
    reviews: 3377,
    price_level: 0,
    popularity: 81,
    transit_minutes: 2,
    transit_line: "VTA Light Rail",
    hours: "Open till 10",
    interests: ["Music", "Food & meals", "Walking", "Art & craft"],
    summary:
      "Various concerts & events are held at this busy open space with water jets & a contemporary statue.",
    quote:
      "Nice little park. Lots of shade. I think it is busy during work hours with traffic, atleast that's what I am told. But there are plenty of places to eat and get cocktails. Cool spot for live events as well.",
    quote_author: "Brian Kitlinger",
    quote_rating: 4,
  },
  {
    id: "grace-community-center",
    google_place_id: "ChIJq6qqqsHMj4ARDVWN9gZuonM",
    name: "Grace Community Center",
    category: "Service",
    address: "488 N 6th St",
    lat: 37.347143,
    lng: -121.89118,
    rating: 4.4,
    reviews: 34,
    price_level: 0,
    popularity: 63,
    transit_minutes: 5,
    transit_line: "Bus 22",
    hours: "Open till 6",
    interests: ["Volunteering", "Food & meals", "Faith groups", "Tutoring"],
    summary: "Community Center with event space · restrooms and step-free entrance.",
    quote:
      "The Staff acted in a very Professional manner. The area was clean and well groomed. In general, an impressive day at Grace Community Center !",
    quote_author: "Bob Sanchi",
    quote_rating: 4,
  },
  {
    // A fixture, not a real listing: it drives the permanently-closed
    // screen. No google_place_id, so refresh-places.mjs leaves it alone.
    id: "bascom-rec-room",
    google_place_id: null,
    name: "Bascom Rec Room",
    category: "Gathering",
    address: "1490 S Bascom Ave",
    lat: 37.3106,
    lng: -121.9316,
    rating: null,
    reviews: 0,
    price_level: 0,
    popularity: 40,
    transit_minutes: 6,
    transit_line: "Bus 25",
    hours: "—",
    interests: ["Basketball", "Music"],
    summary: null,
    quote: null,
    quote_author: null,
    quote_rating: null,
    closed: true,
    closed_on: "4 August",
  },
];

// Adopt-a-third-space: funding requests. Display only — no payment flow.
export const APPLICANTS = [
  {
    id: "olinder-courts",
    name: "Olinder Park basketball courts",
    category: "Sport",
    neighborhood: "East San José",
    lat: 37.3335,
    lng: -121.8686,
    ask: 14000,
    reach: 600,
    need: 88,
    filed: "12 Jun",
    summary:
      "Resurfacing and two new hoops. Ask: $14,000. Serves ~600 residents within a half mile.",
    detail:
      "Two of four hoops are missing rims and the surface floods after rain. The neighborhood association wants resurfacing, two hoops, and a drinking fountain, so the courts can host the summer league again.",
    signals: [
      { label: "Residents within ½ mile", value: "High" },
      { label: "Existing free spaces nearby", value: "Only 1", warn: true },
      { label: "Transit access", value: "Bus 25, 6 min" },
    ],
    contact: "olinder.assoc@example.org",
  },
  {
    id: "alum-rock-reading-room",
    name: "Alum Rock reading room",
    category: "Gathering",
    neighborhood: "Alum Rock",
    lat: 37.3663,
    lng: -121.8235,
    ask: 6200,
    reach: 380,
    need: 81,
    filed: "2 Jul",
    summary:
      "Evening hours for a volunteer-run study space. Ask: $6,200 for staffing through spring.",
    detail:
      "The room is donated and the volunteers are already there. What's missing is a paid coordinator two evenings a week so the space can stay open past six, when students actually need it.",
    signals: [
      { label: "Students within ½ mile", value: "High" },
      { label: "Existing free spaces nearby", value: "Only 2", warn: true },
      { label: "Transit access", value: "Bus 23, 4 min" },
    ],
    contact: "alumrock.reading@example.org",
  },
  {
    id: "guadalupe-cleanup-hub",
    name: "Guadalupe River clean-up hub",
    category: "Service",
    neighborhood: "Downtown",
    lat: 37.3405,
    lng: -121.9016,
    ask: 3400,
    reach: 240,
    need: 74,
    filed: "28 Jul",
    summary: "Tool shed and water station for monthly volunteer days. Ask: $3,400.",
    detail:
      "Volunteers currently haul rakes and water in from their own cars each month. A locked shed and a plumbed water station at the trailhead would roughly double the number of people who stay past an hour.",
    signals: [
      { label: "Volunteer turnout, monthly", value: "Growing" },
      { label: "On-site storage", value: "None", warn: true },
      { label: "Transit access", value: "Light rail, 5 min" },
    ],
    contact: "guadalupe.volunteers@example.org",
  },
];
