-- The catalogue is now generated from the City of San José's open data
-- service rather than hand-maintained (scripts/sync-sanjose.mjs). That
-- retires the last hand-set values on a row and adds the city's identifiers
-- so a re-sync can match a row it has already written.
--
-- `popularity` in particular was documented in 0002 as "the one input that is
-- not measured". It is measured now: it counts the social amenities the city
-- lists as actually being on the site.

alter table public.third_spaces
  add column if not exists city_facility_id text,
  add column if not exists city_location_id text,
  -- Two geographies: `neighborhood` is the fine association area (layer 549),
  -- `district` the city planning area a reader would recognise.
  add column if not exists neighborhood text,
  add column if not exists district text,
  add column if not exists amenities text[] not null default '{}',
  add column if not exists acres numeric(8, 1),
  add column if not exists condition numeric(4, 3) check (condition is null or condition between 0 and 1),
  add column if not exists parking_spaces int,
  -- When refresh-places.mjs last paid for this row, so it can work
  -- oldest-first through a catalogue larger than one run's budget.
  add column if not exists refreshed date;

create index if not exists third_spaces_location_idx
  on public.third_spaces (city_location_id);

-- A site the city lists no amenities for has an *unknown* interactability,
-- not a zero one. Null lets the component drop out and redistribute its
-- weight the way every other missing input does; the old `not null default
-- 50` forced a made-up number in its place.
alter table public.third_spaces
  alter column popularity drop not null,
  alter column popularity drop default;

-- Rows now come from three places, not two.
alter table public.third_spaces drop constraint if exists third_spaces_source_check;
alter table public.third_spaces
  add constraint third_spaces_source_check check (
    source in ('google_places', 'manual_seed', 'sjc-parks', 'sjc-libraries', 'sjc-community-centers')
  );

-- Transit was two hand-typed fields ("6", "Bus 25") that nothing measured.
-- The real number is a Routes API call made per user at render time, and it
-- was never read back off this table.
alter table public.third_spaces
  drop column if exists transit_minutes,
  drop column if exists transit_line;

comment on column public.third_spaces.popularity is
  'Interactability, 0-100. Counts the distinct social amenities the city lists on the site and their total units, log-scaled. Written by scripts/sync-sanjose.mjs from the Park Amenities layer — no longer an estimate.';

comment on column public.third_spaces.condition is
  'The city''s most recent park condition assessment, 0-1, best last. Published per site; drives the invest ranking.';

comment on column public.third_spaces.amenities is
  'City amenity codes actually present on the site (BBALL, PICNIC, POOL, …), from the Park Amenities and Sports Fields layer.';

-- ── adopt_applications ────────────────────────────────────────────────────
-- Dropped. The three rows this table ever held were invented, down to their
-- @example.org contacts. Where-to-invest is now derived from the city's own
-- park condition assessments and Equity Index tracts, ships with the build,
-- and is regenerated by scripts/sync-sanjose.mjs — so there is nothing for a
-- table to hold.

drop table if exists public.adopt_applications;
